In [8]:
import numpy as np

A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

matrix_mul = np.dot(A, B)
print(matrix_mul)
print(f'最大値 : {matrix_mul.max()}')

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
最大値 : 47
